"""
Asynchronous worker service that connects incoming events to the LangGraph instance.
Processes the state, invokes the model, and dispatches the final response.
"""
import logging
from langchain_core.messages import HumanMessage
from backend.agent_core.graph import app_graph
from backend.services.line_messenger import LineMessengerService

logger = logging.getLogger(__name__)

class AgentWorkerService:
    """
    Handles the execution of the AI Agent graph from background tasks.
    """
    
    @staticmethod
    async def process_line_event(event: dict) -> None:
        """
        Parses the LINE event, builds the initial AgentState, runs LangGraph,
        and sends the generated output back to LINE.
        
        Args:
            event (dict): The dictionary containing the LINE webhook event.
        """
        event_type = event.get("type")
        
        # We only handle message events of type text in this foundation phase
        if event_type != "message":
            logger.info(f"Skipping unhandled event type: {event_type}")
            return
            
        message_data = event.get("message", {})
        if message_data.get("type") != "text":
            logger.info(f"Skipping unhandled message type: {message_data.get('type')}")
            return
            
        user_id = event.get("source", {}).get("userId", "")
        reply_token = event.get("replyToken", "")
        user_text = message_data.get("text", "")
        
        if not reply_token:
            logger.warning("Missing replyToken in event. Cannot respond.")
            return

        logger.info(f"Processing message from user {user_id}: {user_text}")

        # Initialize the LangGraph state
        initial_state = {
            "messages": [HumanMessage(content=user_text)],
            "user_id": user_id,
            "extracted_data": None,
            "requires_human_approval": False
        }

        try:
            # Invoke the graph asynchronously (ainvoke)
            # This triggers gemma-4-31b and any database tools automatically
            final_state = await app_graph.ainvoke(initial_state)
            
            # Extract the last AI message from the conversation state
            messages = final_state.get("messages", [])
            if messages:
                final_ai_message = messages[-1].content

                # Ensure the content is safely converted to a string
                if isinstance(final_ai_message, list):
                    # In case of multimodal or block content
                    final_ai_message = " ".join([str(item) for item in final_ai_message if isinstance(item, str) or "text" in str(item)])
                else:
                    final_ai_message = str(final_ai_message)
                
                # Send the answer back to the user on LINE asynchronously
                await LineMessengerService.send_reply(reply_token, final_ai_message)
            else:
                logger.error("No response messages generated by the agent graph.")
                
        except Exception as e:
            error_msg = str(e)
            logger.error(f"Error executing agent graph workflow: {error_msg}")
            # เช็คว่าเป็น Error จากฝั่ง Google Server (500) หรือไม่
            if "500 INTERNAL" in error_msg or "google.genai" in error_msg:
                fallback_message = "ขออภัยครับ ตอนนี้เซิร์ฟเวอร์สมองกล (Google AI) มีผู้ใช้งานหนาแน่น หรือกำลังขัดข้องชั่วคราว รบกวนพิมพ์ถามใหม่อีกครั้งในอีกสักครู่นะครับ 🤖"
            else:
                fallback_message = "ขออภัยครับ ระบบประมวลผลภายในเกิดความผิดพลาด กรุณาลองใหม่อีกครั้ง"
                
            try:
                await LineMessengerService.send_reply(reply_token, fallback_message)
            except Exception as reply_err:
                logger.error(f"Failed to send fallback message: {str(reply_err)}")